local plt=require('praat.plot')
local f,a=plt.subplots(2,2,{title='Plot regression — Юникод',width=8,height=6})
a[1]:plot({-2,-1,0,1,2},{4,1,0,1,4},{label='x^2'})
a[1]:plot({-2,2},{2,2},{color='red',label='reference'})
a[1]:set_title('Lines'):set_xlabel('x'):set_ylabel('y'):legend()
a[2]:scatter({1,2,3},{7,4,9},{size=2,color='#229955'})
a[2]:set_title('Points')
a[3]:bar({1,2,3},{2,-3,4},{width=.7})
a[3]:set_title('Bars')
a[4]:imshow({{0,1,2},{3,4,5}},{extent={0,3,0,2}})
a[4]:set_title('Heatmap')
f:savefig('../../.local-build/lua-plot-test.png',100)
local image=assert(io.open('../../.local-build/lua-plot-test.png','rb'))
local bytes=image:read('a');image:close()
assert(bytes:sub(1,8)=='\137PNG\13\10\26\10')
local width,height=string.unpack('>I4I4',bytes,17)
assert(width==800 and height==600 and #bytes>5000)
local function rejects(action,pattern)
    local ok,err=pcall(action)
    assert(not ok and tostring(err):find(pattern,1,true),tostring(err))
end
rejects(function() f:show() end,'requires GUI')
rejects(function() plt.subplots(0,1) end,'rows')
rejects(function() plt.subplots(100000,100000) end,'rows')
rejects(function() f:savefig('not-supported.pdf') end,'.png')
rejects(function() f:savefig('huge.png',900) end,'dpi')
rejects(function() f:savefig('unsupported.png',72) end,'dpi')
local g,b=plt.subplots()
b:plot({1,2},{1})
rejects(function() g:savefig('bad.png') end,'same nonzero length')
b:clear():plot({1},{0/0})
rejects(function() g:savefig('bad.png') end,'finite')
b:clear():plot({1},{2},{color='invalid'})
rejects(function() g:savefig('bad.png') end,'color')
b:clear():imshow({{1,2},{3}})
rejects(function() g:savefig('bad.png') end,'rectangular')
b:clear():plot({1,2},{3,4})
b:set_xlim(2,1)
rejects(function() g:savefig('bad.png') end,'increasing')
b:set_xlim(0,3):set_ylim(0,5)
g:savefig('../../.local-build/lua-plot-recovery.png',150)
g:close();g:close()
assert(#praat.selected()==0)
print('LUA PLOT TESTS: PASS')
