assert(_VERSION == "Lua 5.5")
assert(require("module").value == 42)
local sound = praat.call("Create Sound from formula", "lua tone", 1, 0, 1, 44100, "0.2*sin(2*pi*440*x)")
assert(type(sound) == "table" and #sound == 1)
assert(praat.call("Get number of samples") == 44100)
assert(math.abs(praat.call("Get total duration") - 1) < 1e-10)
assert(#praat.objects() == 1 and praat.objects()[1].class == "Sound")
local ok, message = pcall(praat.call, "Not a Praat command")
assert(not ok and message:find("Command not available", 1, true))
assert(praat.call("Get number of samples") == 44100)
ok = pcall(praat.select, 99999999)
assert(not ok and praat.selected()[1] == sound[1])
assert(not pcall(os.exit))
assert(not pcall(praat.call, "Quit"))
assert(not pcall(praat.call, "Quit Praat"))
assert(not pcall(package.loadlib, "absent.dll", "open"))
local spectrum = praat.call("To Spectrum", true)
assert(#spectrum == 1 and spectrum[1] ~= sound[1])
praat.select(sound)
local formant = praat.call("To Formant (burg)", 0, 5, 5500, 0.025, 50)
assert(#formant == 1)
praat.select(sound[1])
local copy = praat.call("Copy", "копия")
assert(#copy == 1 and copy[1] ~= sound[1])
local co = coroutine.create(function() local sum=0;for i=1,100000 do sum=sum+i end;return 19 end)
local resumed, value = coroutine.resume(co)
assert(resumed and value == 19)
local sum = 0
for i=1,200000 do sum=sum+i end
assert(sum == 20000100000)
praat.call("Create simple Matrix", "lua_matrix", 2, 3, "row*10+col")
local matrix=praat.call("Get all values")
assert(#matrix==2 and #matrix[1]==3 and matrix[2][3]==23)
local row=praat.call("Get all values in row",2)
assert(#row==3 and row[1]==21)
praat.call("Create Strings as tokens", "привет мир", " ")
assert(praat.call("Get string",1)=="привет")
local strings=praat.call("List all strings")
assert(#strings==2 and strings[2]=="мир")
local all={}
for _, object in ipairs(praat.objects()) do all[#all+1]=object.id end
praat.select(all)
praat.call("Remove")
assert(#praat.objects() == 0)
print("LUA TESTS: PASS", "Юникод", sum)
